In [1]:
# Define the network
import torch.nn as nn
import torch.nn.functional as F

# DNN1: 8+8+8 internal units in 3 hidden layers
class Net_8_8_8(nn.Module):
    def __init__(self):
        super(Net_8_8_8, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 8)
        self.fc2 = nn.Linear(8, 8)
        self.fc3 = nn.Linear(8, 8)
        self.fc4 = nn.Linear(8, 10)

    def forward(self, x):
        x = x.view(-1, 28 * 28) # flatten 
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        return x
    
# DNN3: 20+10+8+8 internal units in 4 hidden layers
class Net_20_10_8_8(nn.Module):
    def __init__(self):
        super(Net_20_10_8_8, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 20)
        self.fc2 = nn.Linear(20, 10)
        self.fc3 = nn.Linear(10, 8)
        self.fc4 = nn.Linear(8, 8)
        self.fc5 = nn.Linear(8, 10)
        
    def forward(self, x):
        x = x.view(-1, 28 * 28) # flatten
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = F.relu(self.fc4(x))
        x = self.fc5(x)
        return x

# DNN5: 20+20+10+10+10 internal units in 5 hidden layers
class Net_20_20_10_10_10(nn.Module):
    def __init__(self):
        super(Net_20_20_10_10_10, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 20)
        self.fc2 = nn.Linear(20, 20)
        self.fc3 = nn.Linear(20, 10)
        self.fc4 = nn.Linear(10, 10)
        self.fc5 = nn.Linear(10, 10)
        self.fc6 = nn.Linear(10, 10)
        
    def forward(self, x):
        x = x.view(-1, 28 * 28) # flatten
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = F.relu(self.fc4(x))
        x = F.relu(self.fc5(x))
        x = self.fc6(x)
        return x
    
#### initialisation sample   

def weights_init(m):
    classname = m.__class__.__name__
    print(classname)
    if classname.find('Conv2d') != -1:
        #print(m.weight.data.shape, m.bias.data.shape)
        nn.init.normal_(m.weight.data, 0.0, 1.0)
        nn.init.constant_(m.bias.data, 0.0)
        # bias is the term in wx + b
    elif classname.find('Linear') != -1:
        nn.init.normal_(m.weight.data, 0.0, 1.0)
        nn.init.constant_(m.bias.data, 0.0)

# net = Net()
    
# print(net)
#net.apply(weights_init)

In [2]:
import torch.optim as optim
import numpy as np

def train(net, max_epoch):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

    for epoch in range(max_epoch):  # loop over the dataset multiple times
        running_loss = 0.0
        for i, data in enumerate(trainloader, 0):
            # get the inputs
            inputs, labels = data
            # zero the parameter gradients
            optimizer.zero_grad()

            # forward + backward + optimize
            outputs = net(inputs)
            loss = criterion(outputs, labels)
            loss.backward() # backpropagation of the weights of linear layers as well as the convolutional layers
            optimizer.step() # dynamic learning rate

            # print statistics
            running_loss += loss.item()
            if i % 400 == 399:    # print every 2000 mini-batches
                print('[%d, %5d] loss: %.3f' %
                      (epoch + 1, i + 1, running_loss / 2000))
                running_loss = 0.0

    print('Finished Training')

In [3]:
def eval(net):
    correct = 0
    total = 0
    flag = True
    all_predicted = []
    all_outputs = np.zeros((10000, 10))
    with torch.no_grad():
        for data in testloader:
            images, labels = data
            if (flag):
    #             print(images)
                single_input = images
                print(images.shape)
                print('------------------------')
                print(labels.shape)
                lable = labels
                flag = False
            outputs = net(images)
            #from pdb import set_trace

            #print(outputs)
            #set_trace()
            all_outputs[len(all_predicted):len(all_predicted)+batch_size] = outputs
            #set_trace()
            _, predicted = torch.max(outputs.data, 1)
            all_predicted = np.concatenate((all_predicted, predicted))
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    print('Accuracy of the network on the 10000 test images: %d %%' % (
        100 * correct / total))
    
    return all_predicted

In [4]:
# Step 1 Load data
import torch
import torchvision
import torchvision.transforms as transforms

batch_size = 64

# load and normalize MNIST
transform = transforms.Compose(
    [transforms.ToTensor()])#,
trainset = torchvision.datasets.MNIST(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=1)

testset = torchvision.datasets.MNIST(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size,
                                         shuffle=False, num_workers=1)

classes = ('0', '1', '2', '3',
           '4', '5', '6', '7', '8', '9')


In [5]:
def save_weights(net_name, layers, num_imgs, all_predicted):
    torch.save(net.state_dict(), "../datasets/%s.pkl" % net_name )
    all_images = testloader.dataset.test_data
    all_true_labels = testloader.dataset.test_labels
    
    # save parameters as json file
    # {
    #   "layers": [2,2,1],
    #   "input": [0.0, 0.0],
    #   "label": 1,
    #   "weights": {
    #     "1": [[1.0,1.0],[1.0,1.0]],
    #     "2": [[1.0], [-2.0]]
    #   },
    #   "biases": {
    #     "1": [[0.0], [-1.0]],
    #     "2": [[0.0]]
    #   }
    # }
    import json

    output = {}
    output_weights = {}
    output_biases = {}

    i = 1
    for param_tensor in net.state_dict():
        if ('weight' in param_tensor):
            output_weights[str(i)] =  net.state_dict()[param_tensor].tolist()
            _T = [list(i) for i in zip(*output_weights[str(i)])]
            output_weights[str(i)] = _T
        if ('bias' in param_tensor):
            output_biases[str(i)] = net.state_dict()[param_tensor].tolist()
            i += 1
    output['weights'] = output_weights
    output['biases'] = output_biases

    for img in range(num_imgs):
        output['layers'] = layers # [input, hidden layers, ..., output]
        output['input'] = all_images[img].flatten().tolist()
        output['label'] = all_true_labels.tolist()[img]
        output['predictedLabel'] = all_predicted[img]
#         from pdb import set_trace

        with open('../datasets/%s/%s-%s-%s.json' % (net_name, img, output['label'], int(output['predictedLabel'])), 'w') as f:
#             set_trace()
            json.dump(output, f)
    
    print("-- Written to file")
    

In [6]:
# Step 2 select a network and train it for 30 epoches

net = Net_8_8_8()
# net = Net_20_10_8_8()
# net = Net_20_20_10_10_10()

train(net, 50)

# Step 3 test accuracy
all_predicted = eval(net)

# Step 4 save the net into file
save_weights("nn1",  [784, 8, 8, 8, 10], 100, all_predicted)
# "nn1",  [784, 8, 8, 8, 10] 91%
# "nn3", [784, 20, 10, 8, 8, 10] 95%
# "nn5", [784, 20, 20, 10, 10, 10, 10] 95%

[1,   400] loss: 0.455
[1,   800] loss: 0.425
[2,   400] loss: 0.339
[2,   800] loss: 0.262
[3,   400] loss: 0.180
[3,   800] loss: 0.150
[4,   400] loss: 0.128
[4,   800] loss: 0.121
[5,   400] loss: 0.113
[5,   800] loss: 0.109
[6,   400] loss: 0.104
[6,   800] loss: 0.100
[7,   400] loss: 0.097
[7,   800] loss: 0.097
[8,   400] loss: 0.093
[8,   800] loss: 0.092
[9,   400] loss: 0.091
[9,   800] loss: 0.086
[10,   400] loss: 0.087
[10,   800] loss: 0.083
[11,   400] loss: 0.082
[11,   800] loss: 0.079
[12,   400] loss: 0.078
[12,   800] loss: 0.079
[13,   400] loss: 0.075
[13,   800] loss: 0.075
[14,   400] loss: 0.073
[14,   800] loss: 0.072
[15,   400] loss: 0.069
[15,   800] loss: 0.071
[16,   400] loss: 0.069
[16,   800] loss: 0.069
[17,   400] loss: 0.068
[17,   800] loss: 0.065
[18,   400] loss: 0.064
[18,   800] loss: 0.065
[19,   400] loss: 0.064
[19,   800] loss: 0.064
[20,   400] loss: 0.061
[20,   800] loss: 0.063
[21,   400] loss: 0.060
[21,   800] loss: 0.061
[22,   400

In [28]:
all_data = [data for data in testloader]
image, label = all_data[0]
print(image[0].shape)
outputs = net(image[0])
print(outputs)
orig = open('../datasets/nn1/22-6-6.json')
orig_json = json.loads(orig.read())
orig_image = orig_json['input']

adv = open('../adversarials/nn1/22-6-6.json')
adv_json = json.loads(adv.read())
adv_image = adv_json['input']

orig = np.array(orig_image)
orig = torch.from_numpy(orig)
orig = orig.view(1,28,28).float()
orig_output = net(orig)
print(orig_output)
_, orig_predicted = torch.max(orig_output.data, 1)
print(orig_predicted)

adv = np.array(adv_image)
adv = torch.from_numpy(adv)
print(adv.shape)
adv = adv.view(1,28,28).float()
print(adv.shape)
adv_output = net(adv)
print(adv_output)
_, adv_predicted = torch.max(adv_output.data, 1)
print(adv_predicted)

torch.Size([1, 28, 28])
tensor([[ -2.6719,  -0.2662,  -2.0035,   5.5266,  -0.7140,   2.8991, -10.7735,
           9.5390,  -1.3102,   5.3323]], grad_fn=<AddmmBackward>)
tensor([[ -140.2411,   417.6232,   305.7504, -1102.7295,   376.5559,  -595.3055,
           532.0024,   139.2141,  -360.5664,  -646.2908]],
       grad_fn=<AddmmBackward>)
tensor([6])
torch.Size([784])
torch.Size([1, 28, 28])
tensor([[ 0.1766,  0.6025,  0.5021, -1.9088,  0.5021,  0.4794,  0.2768,  0.5021,
         -1.4907, -0.8149]], grad_fn=<AddmmBackward>)
tensor([1])
